version: '2'
services:
  # markset:
  #   build: ./markset
  #   restart: always
  #   privileged: true
  #   expose:
  #     - "80"
  camera-server:
    build: ./camera_server
    privileged: true
    ports:
      - "8080:80"

# "i2c_arm=on","spi=on","audio=on"