version: '2'
services:
  markset:
    build: ./markset
    restart: always
    privileged: true
    # volumes:
    #   - .:/usr/src/app/markset
    ports:
      - "80:80"
  # camera-server:
  #   build: ./camera_server
  #   privileged: true
