version: '2'
services:
  # markset:
  #   build: ./markset
  #   restart: always
  #   privileged: true
  #   expose:
  #     - "80"
  camera-server:
    build: ./camera_server
    privileged: true
    expose:
      - "8000"
    labels:
      io.balena.features.kernel-modules: '1'