
race_start: 1800
prestart_timeline: # note this is a compressed timeline, this needs to be 315 min
  - 120:
      music: danger_zone.mp3
      music_timeout: 10
      function: Countdown
  - 105:
      music: siren.mp3
      music_timeout: 5
      function: ShowOrder
  - 65:
      function: FiveToots
  - 60:
      function: Countdown
  - 30: 
      music: siren.mp3
      music_timeout: 5
      function: ShowOrder
  - 10:
      audio: tornado.mp3
      function: Countdown
      music_timeout: 4
  - 5:
      function: CountdownToots
  - 0:
      function: BeginRace
class_timeline: # note this is a compressed timeline, this needs to be 3 min
  - 90:  
      function: ClassFlagUp
  - 75:  
      function: ShowOrderQuick
  - 70:
      function: PrepFlageUp
  - 65:  
      function: ShowOrderQuick
  - 45:
      function: PrepFlageDown
  - 40:  
      function: ShowOrderQuick
  - 30:
      function: ThreeToots
  - 20:
      function: TwoToots
  - 10:
      function: OneToot
  - 5:
      function: CountdownToots
order: 
  - name: ' NSB'
    color: 0x002200
    audio: danger_zone.mp3
    bitmap: bitmaps/nsb.bmp
  - name: ' NSA/C22'
    color: 0x0000FF
    color2: 0x6a0dad
    audio: sample.wav 
  - name: ' PORTSM'
    color: 0x662200
    audio: sample.wav 
    bitmap: bitmaps/nsb.bmp
  - name: ' SPIN'
    color: 0xC29200
    audio: sample.wav 
  - name: ' J-22'
    color: 0xCC0000
    audio: sample.wav 
  - name: ' J-24'
    color: 0x590036
    audio: sample.wav