
race_start: 1800
prestart_timeline: # note this is a compressed timeline, this needs to be 15 min
  - 120:
      music: danger_zone.mp3
      music_timeout: 10
  - 105:
      function: ShowOrder
      music: siren.mp3
      music_timeout: 5
  - 65:
      music: five_toots.mp3
      music_timeout: 7  #five short and one long
  - 30: 
      music: siren.mp3
      music_timeout: 5
  - 10:
      music: tornado.mp3
      music_timeout: 3
  - 5:
      music: five_toots.mp3
      music_timeout: 7  #five short and one long
class_timeline: # note this is a compressed timeline, this needs to be 3 min
  - 90:  
      function: ClassFlagUp
  - 89:  
      function: ClassTunes # this is dumb
  - 75:  
      function: ShowOrderQuick
  - 69:  
      function: ClassFlagUp # this is dumb
  - 65:
      function: PrepFlageUp
      music: long_toot.mp3
      music_timeout: 4 
  - 60:  
      function: ShowOrderQuick
  - 54:  
      function: PrepFlageUp
  - 45:
      function: PrepFlageDown
      music: long_toot.mp3
      music_timeout: 4 
  - 40:  
      function: ShowOrderQuick
  - 39:
      function: PrepFlageDown
  - 30:
      music: three_toots.mp3 self.horn_.play(sail_class.music)
      music: two_toots.mp3
      music_timeout: 3  
  - 10:
      music: long_toot.mp3
      music_timeout: 2  
  - 5:
      music: five_toots.mp3
      music_timeout: 7  #five short and one long
order: 
  - name: ' NSB'
    color: 0x002200
    music: danger_zone.mp3
    bitmap: bitmaps/nsb.bmp
  - name: ' NSA/C22'
    color: 0x0000FF
    color2: 0x6a0dad
    music: sample.wav 
  - name: ' PORTSM'
    color: 0x662200
    music: sample.wav 
    bitmap: bitmaps/nsb.bmp
  - name: ' SPIN'
    color: 0xC29200
    music: sample.wav 
  - name: ' J-22'
    color: 0xCC0000
    music: sample.wav 
  - name: ' J-24'
    color: 0x590036
    music: sample.wav