
race_start: 1800
prestart_timeline: 

  - 1800:
      function: ShowOrder
      music: one_toot.mp3
  - 1740:
      function: ShowOrder
      music: one_toot.mp3
  - 1680:
      function: ShowOrder
      music: one_toot.mp3
  - 1620:
      function: ShowOrder
      music: one_toot.mp3
  - 1560:
      function: ShowOrder
      music: one_toot.mp3
  - 1500:
      function: ShowOrder
      music: one_toot.mp3
  - 1440:
      function: ShowOrder
      music: one_toot.mp3
  - 1380:
      function: ShowOrder
      music: one_toot.mp3
  - 1320:
      function: ShowOrder
      music: one_toot.mp3
  - 1260:
      function: ShowOrder
      music: one_toot.mp3
  - 1200:
      function: ShowOrder
      music: siren.mp3
      music_timeout: 10 
  - 1140:
      function: ShowOrder
      music: one_toot.mp3
  - 1080:
      function: ShowOrder
      music: one_toot.mp3
  - 1020:
      function: ShowOrder
      music: one_toot.mp3
  - 960:
      function: ShowOrder
      music: one_toot.mp3
  - 900:
      function: ShowOrder
      music: one_toot.mp3
  - 840:
      function: ShowOrder
      music: one_toot.mp3
  - 780:
      function: ShowOrder
      music: one_toot.mp3
  - 720:
      function: ShowOrder
      music: one_toot.mp3
  - 660:
      function: ShowOrder
      music: one_toot.mp3
  - 600:
      function: ShowOrder
      music: one_toot.mp3
  - 540:
      function: ShowOrder
      music: one_toot.mp3
  - 480:
      function: ShowOrder
      music: one_toot.mp3
  - 420:
      function: ShowOrder
      music: one_toot.mp3
  - 360:
      function: ShowOrder
      music: one_toot.mp3
  - 300:
      function: ShowOrder
      music: siren.mp3
      music_timeout: 10 
  - 240:
      function: ShowOrder
      music: one_toot.mp3
  - 180:
      function: ShowOrder
      music: one_toot.mp3
  - 120:
      function: ShowOrder
      music: one_toot.mp3
  - 60:
      function: ShowOrder
  - 59:
      music: siren.mp3
      music_timeout: 10 
  - 30:
      function: ShowOrder
  - 5:
      music: five_toots.mp3
      music_timeout: 7  #five short and one long
class_timeline: # note this is a compressed timeline, this needs to be 3 min
  - 180:  
      function: ClassFlagUp
  - 179:  
      function: ClassTunes 
  - 150:  
      function: ShowOrderQuick
  - 144:  
      function: ClassFlagUp # this is dumb
  - 120:
      function: PrepFlageUp
      music: long_toot.mp3
      music_timeout: 4 
  - 90:  
      function: ShowOrderQuick
  - 87:  
      function: PrepFlageUp
  - 60:
      function: PrepFlageDown
      music: long_toot.mp3
      music_timeout: 4 
  - 30:
      music: three_toots.mp3 
      music_timeout: 4  
  - 20:
      music: two_toots.mp3
      music_timeout: 3  
  - 10:
      music: one_toot.mp3
      music_timeout: 2  
  - 5:
      music: five_toots.mp3
      music_timeout: 7  #five short and one long


order: 
  - name: 'JAM '
    color: 0x002200
    music: welcome_to_the_jungle.mp3
    bitmap: bitmaps/nsb.bmp
    course: 'P'
    laps: '1'
  - name: 'PORT'
    color: 0x0000FF
    music: Thunderstruck.mp3 
    bitmap: bitmaps/nsb.bmp
    course: 'P'
    laps: '1'
  - name: 'SPNS'
    color: 0xCC0000
    music: pour_some_sugar_on_me.mp3 
    course: 'P'
    laps: '1'
  - name: 'SPNG'
    color: 0x351C75
    music: pour_some_sugar_on_me.mp3 
    course: 'M'
    laps: '3'
#   - name: 'J-22'
#     color: 0xCC0000
#     music: welcome_to_the_jungle.mp3 
#     course: 'J'
#     laps: '1'
#   - name: ' J-24'
#     color: 0x662200
#     music: sample.wav
