
race_start: 1800
prestart_timeline: 

  - 1800:
      function: ShowOrder
      music: one_toot.mp3
  - 1770:
      function: ShowOrder
  - 1740:
      function: ShowOrder
  - 1710:
      function: ShowOrder
  - 1680:
      function: ShowOrder
  - 1650:
      function: ShowOrder
  - 1620:
      function: ShowOrder
  - 1590:
      function: ShowOrder
  - 1560:
      function: ShowOrder
  - 1530:
      function: ShowOrder
  - 1500:
      function: ShowOrder
      music: one_toot.mp3
  - 1470:
      function: ShowOrder
  - 1440:
      function: ShowOrder
  - 1410:
      function: ShowOrder
  - 1380:
      function: ShowOrder
  - 1350:
      function: ShowOrder
  - 1320:
      function: ShowOrder
  - 1290:
      function: ShowOrder
  - 1260:
      function: ShowOrder
  - 1230:
      function: ShowOrder
  - 1200:
      function: ShowOrder
      music: one_toot.mp3
  - 1170:
      function: ShowOrder
  - 1140:
      function: ShowOrder
  - 1110:
      function: ShowOrder
  - 1080:
      function: ShowOrder
  - 1050:
      function: ShowOrder
  - 1020:
      function: ShowOrder
  - 990:
      function: ShowOrder
  - 960:
      function: ShowOrder
  - 930:
      function: ShowOrder
  - 900:
      function: ShowOrder
      music: one_toot.mp3
  - 870:
      function: ShowOrder
  - 840:
      function: ShowOrder
  - 810:
      function: ShowOrder
  - 780:
      function: ShowOrder
  - 750:
      function: ShowOrder
  - 720:
      function: ShowOrder
  - 690:
      function: ShowOrder
  - 660:
      function: ShowOrder
  - 630:
      function: ShowOrder
  - 615:
      function: ShowOrder
  - 600:
      function: ShowOrder
      music: one_toot.mp3
  - 570:
      function: ShowOrder
  - 540:
      function: ShowOrder
  - 510:
      function: ShowOrder
  - 480:
      function: ShowOrder
  - 450:
      function: ShowOrder
  - 420:
      function: ShowOrder
  - 390:
      function: ShowOrder
  - 360:
      function: ShowOrder
  - 330:
      function: ShowOrder
  - 300:
      function: ShowOrder
      music: siren.mp3
      music_timeout: 5
  - 270:
      function: ShowOrder
  - 240:
      function: ShowOrder
      music: one_toot.mp3
  - 210:
      function: ShowOrder
  - 180:
      function: ShowOrder
      music: one_toot.mp3
  - 150:
      function: ShowOrder
  - 120:
      function: ShowOrder
      music: one_toot.mp3
  - 90:
      function: ShowOrder
  - 60:
      function: ShowOrder
      music: one_toot.mp3
  - 59:
      music: siren.mp3
      music_timeout: 5 
  - 30:
      function: ShowOrder
  - 5:
      music: five_toots.mp3
      music_timeout: 7  #five short and one long
class_timeline: # note this is a compressed timeline, this needs to be 3 min
  - 180:  
      function: ClassFlagUp
  - 179:  
      function: ClassTunes 
  - 150:  
      function: ShowOrderQuick
  - 120:
      function: PrepFlageUp
      music: long_toot.mp3
      music_timeout: 4 
  - 90:  
      function: ShowOrderQuick
  - 60:
      function: PrepFlageDown
      music: long_toot.mp3
      music_timeout: 4 
  - 30:
      music: three_toots.mp3 
      music_timeout: 4  
  - 20:
      music: two_toots.mp3
      music_timeout: 3  
  - 10:
      music: one_toot.mp3
      music_timeout: 2  
  - 5:
      music: five_toots.mp3
      music_timeout: 7  #five short and one long


order: 
  - name: 'PORT'
    color: 0x000011
    music: Thunderstruck.mp3 
    course: 'L'
    laps: '2'
  - name: 'JAM '
    color: 0x000500
    music: welcome_to_the_jungle.mp3
    course: 'L'
    laps: '2'
  - name: 'SPIN'
    color: 0x030000
    music: pour_some_sugar_on_me.mp3 
    course: 'L'
    laps: '2'
  - name: 'J-22'
    color: 0x030103
    music: eye_of_the_tiger.mp3 
    course: 'S'
    laps: '3'
#   - name: ' J-24'
#     color: 0x662200
#     music: sample.wav
