
min_between_race: 1
timeline:
  - 1800.00:
      audio: countdown.mp3
      function: 'Countdown'
      num_minutes: 15
  - 1814.00:
      audio: tornado.mp3
      function: 'Countdown'
      num_minutes: 1
  - 1814.50:
      audio: ten_beeps.mp3
      function: 'Countdown'
      num_minutes: 0
      num_seconds: 10
  - 1815.00:
      function: 'BeginRacing'

order: 
  - name: 'NS-B'
    color: 0x00FF00
    audio: sailing.mp3
    bitmap: bitmaps/nsb.bmp
  - name: 'NS-A & C-22'
    color: 0x0000FF
    color2: 0x6a0dad
    audio: some_song.mp3 
  - name: 'PM'
    color: 0x964B00
    audio: sailing.mp3
    bitmap: bitmaps/nsb.bmp
  - name: 'SPIN'
    color: 0xFFDB58
    audio: some_song.mp3
  - name: 'J22'
    color: 0xFF0000
    audio: some_song.mp3
  - name: 'J24'
    color: 0xFFC0CB
    audio: some_song.mp3