
min_between_race: 1
timeline:
  - 1800.00:
      audio: countdown.mp3
      function: 'Countdown'
      num_minutes: 15
  - 1814.00:
      audio: tornado.mp3
      function: 'Countdown'
      num_minutes: 1
  - 1814.50:
      audio: ten_beeps.mp3
      function: 'Countdown'
      num_minutes: 0
      num_seconds: 10
  - 1815.00:
      function: 'BeginRacing'

order: 
  - name: ' NSB'
    color: 0x097969
    audio: sailing.mp3
    bitmap: bitmaps/nsb.bmp
  - name: ' NSA/C22'
    color: 0x0000FF
    color2: 0x6a0dad
    audio: some_song.mp3 
  - name: ' Portsm'
    color: 0x964B00
    audio: sailing.mp3
    bitmap: bitmaps/nsb.bmp
  - name: ' SPIN'
    color: 0xC29200
    audio: some_song.mp3
  - name: ' J-22'
    color: 0xCC0000
    audio: some_song.mp3
  - name: ' J-24'
    color: 0x590036
    audio: some_song.mp3