version: "2.3"

services:
  # mavros:
  #   container_name: mavros
  #   image: markset-mavros-rolling:latest
  #   command: ros2 launch --wait mavros apm2.launch fcu_url:=udp://@localhost
  #   stdin_open: true
  #   tty: true
  #   network_mode: "host"
  #   privileged: true
  #   restart: unless-stopped
  #   depends_on:
  #     - "ros"
  #   volumes:
  #     - /dev:/dev
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw
  #     - /home/ubuntu/markset:/home/root/markset
  #   environment:
  #     DISPLAY: ${DISPLAY}
  #     QT_X11_NO_MITSHM: 1

  rosbridge:
    container_name: rosbridge
    image: markset-mavros-rolling:latest
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml use_compression:=True
    stdin_open: true
    restart: unless-stopped
    tty: true
    network_mode: "host"
    privileged: true
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/ubuntu/markset:/home/root/markset
    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: 1
  